services:

  postgres:
    restart: always
    image: postgres:14-alpine
    container_name: postgres_MH
    ports:
      - 5432:5432
    volumes:
      - ./backend/app/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.volumes/postgres/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=monsterHunter_DB
      - PGDATA=/var/lib/postgresql/data/
  
  node_express:
    restart: always
    container_name: express_MH
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    depends_on:
      - postgres