services:

  postgres:
    restart: always
    image: postgres:14-alpine
    container_name: postgres_MH
    ports:
      - 5432:5432
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=monsterHunter_DB
      - PGDATA=/var/lib/postgresql/data/